version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=sns_local_user
      - MYSQL_PASSWORD=sns_local_password
      - MYSQL_DATABASE=sns_local
    volumes:
      - sns-local-data:/var/lib/mysql

volumes:
  sns-local-data:
